CREATE TABLE IF NOT EXISTS members (
    email         VARCHAR(255) PRIMARY KEY,
    nickname      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'USER',
    status        VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS bot_api_keys (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      VARCHAR(255) NOT NULL REFERENCES members(email) ON DELETE CASCADE,
    exchange       VARCHAR(20) NOT NULL DEFAULT 'BITGET',
    bot_target     VARCHAR(20) NOT NULL DEFAULT 'MAIN',
    api_key_enc    TEXT NOT NULL,
    secret_key_enc TEXT NOT NULL,
    passphrase_enc TEXT NOT NULL,
    label          VARCHAR(100),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bot_api_keys_member
    ON bot_api_keys(member_id, exchange, bot_target);

CREATE TABLE IF NOT EXISTS spot_manual_cost (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  VARCHAR(255) NOT NULL REFERENCES members(email) ON DELETE CASCADE,
    exchange   VARCHAR(20) NOT NULL DEFAULT 'BITGET',
    coin       VARCHAR(30) NOT NULL,
    avg_cost   NUMERIC(24, 8) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (member_id, exchange, coin)
);
